CREATE DATABASE CLUBPIPITA
GO
USE CLUBPIPITA
GO 
CREATE TABLE ROL(
CODIGO VARCHAR(50) PRIMARY KEY,
NOMBREROL VARCHAR(50),
DESCRIPCION VARCHAR(50)
)
GO
CREATE TABLE USUARIO(
CORREO VARCHAR(50) PRIMARY KEY,
CONTARSENA VARCHAR(50),
CODROL VARCHAR(50) FOREIGN KEY REFERENCES ROL(CODIGO)
)
GO
CREATE TABLE PERSONA(
ID VARCHAR(50) PRIMARY KEY,
NOMBRE VARCHAR(50),
APELLIDO VARCHAR(50),
TELEFONO VARCHAR(50),
USUARIO VARCHAR(50) FOREIGN KEY REFERENCES USUARIO(CORREO)
)
GO
CREATE TABLE EQUIPO(
CODIGO VARCHAR(50) PRIMARY KEY,
NOMBRE VARCHAR(50),
)
GO
CREATE TABLE JUGADOR (
NUMDORSAL VARCHAR(4),
ID VARCHAR(50) FOREIGN KEY REFERENCES PERSONA(ID),
PRIMARY KEY (ID),
CODEQUIPO VARCHAR(50) FOREIGN KEY REFERENCES EQUIPO(CODIGO)
)
GO
CREATE TABLE ARBITRO(
FUNCION VARCHAR(50),
ID VARCHAR(50) FOREIGN KEY REFERENCES PERSONA(ID),
PRIMARY KEY (ID)
)
GO
CREATE TABLE DT (
DIPLOMADOS VARCHAR(50),
ID VARCHAR(50) FOREIGN KEY REFERENCES PERSONA(ID),
PRIMARY KEY (ID)
)
GO
CREATE TABLE ESTADISTICAS(
IDJUGADOR VARCHAR(50) FOREIGN KEY REFERENCES JUGADOR(ID),
PRIMARY KEY (IDJUGADOR),
CANTAMARRILLAS INT,
CANTROJAS INT,
CANTGOLES INT,
CANTFALTAS INT
)
GO
CREATE TABLE TORNEO(
CODIGO VARCHAR(50) PRIMARY KEY,
FECHAINICIO DATE,
FECHAFINAL DATE
)
GO
CREATE TABLE FASEGRUPOS(
CODIGO VARCHAR(50) PRIMARY KEY,
FECHAINICIO DATE,
FECHAFINAL DATE,
CODFASEGRUPO VARCHAR(50) FOREIGN KEY REFERENCES TORNEO(CODIGO)
)
GO
CREATE TABLE PARTIDO(
CODIGO VARCHAR(50) PRIMARY KEY,
FECHA DATE,
IDARBRITO VARCHAR(50) FOREIGN KEY REFERENCES ARBITRO(ID),
CODFASEGRUPO VARCHAR(50) FOREIGN KEY REFERENCES FASEGRUPOS(CODIGO)
)
GO
CREATE TABLE PARTIDOJUGADO(
CODIGOPARTIDO VARCHAR(50) FOREIGN KEY REFERENCES PARTIDO(CODIGO),
CODIGOEQUIPO VARCHAR(50) FOREIGN KEY REFERENCES EQUIPO(CODIGO),
PRIMARY KEY (CODIGOPARTIDO,CODIGOEQUIPO),
MARCADOR VARCHAR(10),
GANADOR VARCHAR(50)
)
GO
CREATE TABLE PATROCINADOR(
ID VARCHAR(50) PRIMARY KEY,
NOMBRE VARCHAR(50),
DESCRIPCION VARCHAR(50)
)
GO 
CREATE TABLE PATROCINADOREQUIPO(
IDPATROCINADOR VARCHAR(50) FOREIGN KEY REFERENCES PATROCINADOR(ID),
CODEQUIPO VARCHAR(50) FOREIGN KEY REFERENCES EQUIPO(CODIGO),
PRIMARY KEY (IDPATROCINADOR,CODEQUIPO)
)

